export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  CONCURRENT_SAVE_CONFLICT: "CONCURRENT_SAVE_CONFLICT",
  UNIVERSE_OVERFLOW: "UNIVERSE_OVERFLOW",
  PREVIEW_RECOMPUTING: "PREVIEW_RECOMPUTING",
  TRACK_LOCKED: "TRACK_LOCKED",
  INVALID_TRACK_DURATION: "INVALID_TRACK_DURATION",
  PREVIEW_WORKER_FAILED: "PREVIEW_WORKER_FAILED"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
